#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left_Drive,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     Right_Drive,   tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    TestServo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c" //Adds the Joystick header file

void ServoFwd()// A Refrence for the RobotC program to call
{
	servo[TestServo] = [TestServo] + 5;
}
void ServoBack()
{
	servo[TestServo] = [TestServo] - 5;
}


task main()
{
	while (true) //The program will run forever, or until it is stopped manually
	{
		getJoystickSettings(joystick); //Retrieve joystick values
		if (abs(joystick.joy1_y1) > 5) //A boolean if statement that works as a deadband. The deadband is +- 5.
		{
			motor[Left_Drive] = joystick.joy1_y1;
		}
		else
		{
			motor[Left_Drive] = 0;
		}
		if (abs(joystick.joy1_y2) > 5)
		{
			motor[Right_Drive] = joystick.joy1_y2;
		}
		else
		{
			motor[Right_Drive] = 0;
		}




		//Below is an example of a simple program that can use Logetic Buttons by calling the void functions above

		if (joy1Btn(1) == 1)//Heres the button command. It says "Check to see if Joystick 1 Button (1) signal is equal to 1"
		{
			ServoFwd(); // Calls the "void ServoFwd" command on (line 15) when the X btn is pressed
		}

		if (joy1Btn(2) == 1)
		{
			ServoBack();
		}

	}



}
