#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, driveLeft)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C2_1,     DriveLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     DriveRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);

		if (abs(joystick.joy1_y1) > 8)
		{
			motor[LeftDrive] = joystick.joy1_y1;
		}
		else
		{
			motor[LeftDrive] = 0;
		}
		if (abs(joystick.joy1_y2) > 8)
		{
			motor[RightDrive] = joystick.joy1_y2;
		}
		ielse
		{
			motor[RightDrive] = 0;
		}

	}
}
