#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive,     tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C1_2,     Arm1,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     RightDrive,    tmotorTetrix, openLoop, driveRight)
#pragma config(Motor,  mtr_S1_C2_2,     Arm2,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    Claw1,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_6,    Claw2,                tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{

	while(true)
	{
		getJoystickSettings(joystick);

		if (abs(joystick.joy1_y1) > 8)
		{
			motor[LeftDrive] = joystick.joy1_y1;
		}
		else
		{
			motor[LeftDrive] = 0;
		}
		if (abs(joystick.joy1_y2) > 8)
		{
			motor[RightDrive] = joystick.joy1_y2;
		}
		else
		{
			motor[RightDrive] = 0;
		}

		if (joystick.joy1_TopHat == 0)
		{
			motor[Arm1] = 75;
		}
		if (joystick.joy1_TopHat == -1)
		{
			motor[Arm1] = 0;
		}
		if (joystick.joy1_TopHat == 4)
		{
			motor[Arm1] = -75;
		}
		if (joystick.joy1_TopHat == 5)
		{
			motor[Arm2] = joystick.joy2_y2;
		}
		if (joystick.joy1_TopHat == 2)
		{
			motor[Arm1] = 75;
		}
		if (joy2Btn(01) == 1)
		{
			servo[Claw1] = 0;
			servo[Claw2] = 255;
		}
		else
		{
			servo[Claw1] = 127;
			servo[Claw2] = 127;
		}
		if (joy2Btn(02) == 1)
		{
			servo[Claw1] = 255;
			servo[Claw2] = 0;
		}
	}
}
