#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     Button2,        sensorTouch)
#pragma config(Sensor, S3,     Button3,        sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     Control,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Robot_Motor,   tmotorTetrix, openLoop)
#pragma config(MotorPidSetting,  motorA,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
#pragma config(MotorPidSetting,  motorB,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
#pragma config(MotorPidSetting,  motorC,  255, 255, 65535, 255, 255,   65535, 65535, 65535)
#pragma config(Servo,  srvo_S1_C2_1,    Control_Servo,        tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    Robot_Servo,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/* This program has been designed and configured for the Test_Robot to help students test
	servos and motors
	*/
	int test = ServoValue[Control_Servo];
	int test2 = ServoValue[Control_Servo];
	int test3 = ServoValue[Robot_Servo];
	int test4 = ServoValue[Robot_Servo];
	while (true)
	{
		if (SensorValue(Button2) < 1000)
		{
			test = ServoValue[Control_Servo] + 1;
			servo[Control_Servo] = test;
			test3 = ServoValue[Robot_Servo] + 1;
			servo[Robot_Servo] = test3;
		}
		if (SensorValue(Button3) <1000)
		{
			test2 = ServoValue[Control_Servo] - 1;
			servo[Control_Servo] = test2;
			test4 = ServoValue[Robot_Servo] - 1;
			servo[Robot_Servo] = test4;
		}

	}
}
